language: ruby
rvm:
- 2.1

before_install:
- openssl aes-256-cbc -K $encrypted_b7b6a058a6f4_key -iv $encrypted_b7b6a058a6f4_iv -in githubpagesites-0405247c814f.json.enc -out githubpagesites-0405247c814f.json -d
- if [ ! -d ${HOME}/google-cloud-sdk ]; then
     curl https://sdk.cloud.google.com | bash;
  fi
- gcloud auth activate-service-account --key-file githubpagesites-0405247c814f.json

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - release-1.1     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer PATH=$PATH:${HOME}/google-cloud-sdk/bin

sudo: false # route your build to the container-based infrastructure for a faster build

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

install:
- gcloud components install gsutil
- gcloud config set project githubpagessites

script:
- jekyll build
- gsutil rsync -d -r _site gs://kubernetes-docs-v1-1
